import { Company, Sector, Stage, SignalStatus } from "@/types";

function getRecentDate(daysAgo: number): string {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
}

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "Acme AI",
    website: "https://acmeai.com",
    sector: "AI/ML",
    stage: "Series A",
    description: "Enterprise AI platform for automated workflows",
    founded: 2021,
    employees: "50-100",
    location: "San Francisco, CA",
    lastFunding: "2024-01",
    lastFundingAmount: "$15M",
    signals: "positive",
    lastActivity: getRecentDate(2),
  },
  {
    id: "2",
    name: "DataFlow Systems",
    website: "https://dataflow.io",
    sector: "Enterprise Software",
    stage: "Series B",
    description: "Real-time data processing infrastructure",
    founded: 2019,
    employees: "100-250",
    location: "New York, NY",
    lastFunding: "2023-11",
    lastFundingAmount: "$45M",
    signals: "neutral",
    lastActivity: getRecentDate(5),
  },
  {
    id: "3",
    name: "FinSecure",
    website: "https://finsecure.com",
    sector: "Fintech",
    stage: "Seed",
    description: "Banking security and fraud prevention",
    founded: 2022,
    employees: "10-50",
    location: "Austin, TX",
    lastFunding: "2024-02",
    lastFundingAmount: "$5M",
    signals: "positive",
    lastActivity: getRecentDate(1),
  },
  {
    id: "4",
    name: "HealthSync",
    website: "https://healthsync.ai",
    sector: "Healthcare",
    stage: "Series A",
    description: "AI-powered patient data synchronization",
    founded: 2020,
    employees: "50-100",
    location: "Boston, MA",
    lastFunding: "2023-12",
    lastFundingAmount: "$20M",
    signals: "neutral",
    lastActivity: getRecentDate(8),
  },
  {
    id: "5",
    name: "CodeForge",
    website: "https://codeforge.dev",
    sector: "DevTools",
    stage: "Pre-Seed",
    description: "Developer productivity platform",
    founded: 2023,
    employees: "1-10",
    location: "Remote",
    lastFunding: "2024-03",
    lastFundingAmount: "$2M",
    signals: "positive",
    lastActivity: getRecentDate(0),
  },
  {
    id: "6",
    name: "RetailMind",
    website: "https://retailmind.com",
    sector: "E-commerce",
    stage: "Series C",
    description: "E-commerce analytics and optimization",
    founded: 2018,
    employees: "250-500",
    location: "Seattle, WA",
    lastFunding: "2023-09",
    lastFundingAmount: "$75M",
    signals: "negative",
    lastActivity: getRecentDate(15),
  },
  {
    id: "7",
    name: "CloudVault",
    website: "https://cloudvault.io",
    sector: "SaaS",
    stage: "Series B",
    description: "Enterprise cloud storage and backup",
    founded: 2019,
    employees: "100-250",
    location: "San Francisco, CA",
    lastFunding: "2023-10",
    lastFundingAmount: "$50M",
    signals: "neutral",
    lastActivity: getRecentDate(12),
  },
  {
    id: "8",
    name: "MediTrack",
    website: "https://meditrack.ai",
    sector: "Healthcare",
    stage: "Seed",
    description: "Medical device tracking and compliance",
    founded: 2021,
    employees: "10-50",
    location: "Chicago, IL",
    lastFunding: "2024-01",
    lastFundingAmount: "$8M",
    signals: "positive",
    lastActivity: getRecentDate(3),
  },
  {
    id: "9",
    name: "PayFlow",
    website: "https://payflow.com",
    sector: "Fintech",
    stage: "Series A",
    description: "B2B payment processing platform",
    founded: 2020,
    employees: "50-100",
    location: "New York, NY",
    lastFunding: "2023-11",
    lastFundingAmount: "$25M",
    signals: "neutral",
    lastActivity: getRecentDate(7),
  },
  {
    id: "10",
    name: "DevOps Pro",
    website: "https://devopspro.io",
    sector: "DevTools",
    stage: "Series A",
    description: "CI/CD automation platform",
    founded: 2021,
    employees: "50-100",
    location: "San Francisco, CA",
    lastFunding: "2024-02",
    lastFundingAmount: "$18M",
    signals: "positive",
    lastActivity: getRecentDate(4),
  },
  {
    id: "11",
    name: "ConsumerApp",
    website: "https://consumerapp.com",
    sector: "Consumer",
    stage: "Seed",
    description: "Mobile-first consumer engagement platform",
    founded: 2022,
    employees: "10-50",
    location: "Los Angeles, CA",
    lastFunding: "2024-01",
    lastFundingAmount: "$6M",
    signals: "none",
    lastActivity: getRecentDate(20),
  },
  {
    id: "12",
    name: "EnterpriseAI",
    website: "https://enterpriseai.com",
    sector: "Enterprise Software",
    stage: "Series D+",
    description: "Enterprise AI solutions for Fortune 500",
    founded: 2017,
    employees: "500+",
    location: "San Francisco, CA",
    lastFunding: "2023-08",
    lastFundingAmount: "$150M",
    signals: "neutral",
    lastActivity: getRecentDate(6),
  },
];

export const sectors: Sector[] = [
  "Enterprise Software",
  "Consumer",
  "Fintech",
  "Healthcare",
  "AI/ML",
  "DevTools",
  "E-commerce",
  "SaaS",
  "Other",
];

export const stages: Stage[] = [
  "Pre-Seed",
  "Seed",
  "Series A",
  "Series B",
  "Series C",
  "Series D+",
  "Growth",
];

